import type { Metadata } from "next";
import { Header } from "@/components/custom/header";
import { Container } from "@/components/custom";

export const metadata: Metadata = {
  title: "Shalom | Checkout",
  description: "Generated by create next app",
};

export default function CheckoutLayout({ children }: {children: React.ReactNode}) {
  return (
    <main className="min-h-screen bg-white">
        <Container>
            <Header hasCart={false} hasSearch={false} className="bg-white"></Header>
            {children}
        </Container>
    </main>
  );
}
